"""Build the Kaggle kernel for the DOFA run: train/dofa/dofa-kaggle.ipynb + kernel-metadata.json.

    python scripts/make_dofa_notebook.py [--user vinayakameta] [--epochs 5]

Same rules as make_train_notebook.py: the two scripts are EMBEDDED (base64) so nothing is
uploaded by hand, the notebook is never edited after generation, and the first cell says
which card it landed on. Unlike the Qwen kernels this one does not need sm_75 - a P100 runs
a ViT-B in fp16 fine - so the accelerator reset on push is harmless here.
"""
import argparse
import base64
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EMBED = ["scripts/dofa_model.py", "scripts/dofa_reben.py"]


def code(*lines):
    return {"cell_type": "code", "metadata": {}, "execution_count": None, "outputs": [], "source": list(lines)}


def md(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": list(lines)}


def payload():
    files = {}
    for rel in EMBED:
        with open(os.path.join(ROOT, rel), "rb") as fh:
            files[os.path.basename(rel)] = base64.b64encode(fh.read()).decode()
    return json.dumps(files)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--user", default="vinayakameta")
    ap.add_argument("--epochs", type=int, default=5)
    ap.add_argument("--slug", default="satquery-dofa-reben")
    a = ap.parse_args()
    cells = [
        md("# DOFA ViT-B/16 on reBEN Lithuania/Summer - probe, fine-tune, controls\n",
           "Generated by `scripts/make_dofa_notebook.py`. Do not edit here; regenerate.\n"),
        code(
            "# ---- 1. preflight ----\n",
            "import os\n",
            "os.environ['CUDA_VISIBLE_DEVICES'] = '0'\n",
            "import time, torch\n",
            "T_START = time.time()\n",
            "assert torch.cuda.is_available(), 'no GPU - set Accelerator in Settings'\n",
            "cap = torch.cuda.get_device_capability(0)\n",
            "print('card:', torch.cuda.get_device_name(0), '| capability', cap,\n",
            "      '| %.1f GB' % (torch.cuda.get_device_properties(0).total_memory / 1e9))\n",
            "# MEASURED 7 Sep (v1 of this kernel): Kaggle's torch build supports sm_70+ only, so a\n",
            "# P100 (sm_60) dies at the FIRST cuda kernel with 'no kernel image is available' -\n",
            "# for plain fp16 ViT-B too, not just 4-bit. A push resets the accelerator to P100;\n",
            "# set GPU T4 x2 in the browser, then Save & Run All.\n",
            "assert cap >= (7, 0), 'landed on a %s (sm_%d%d) - set Accelerator to GPU T4 x2 and rerun' % (\n",
            "    torch.cuda.get_device_name(0), cap[0], cap[1])\n",
        ),
        code(
            "# ---- 2. deps + the two embedded scripts ----\n",
            "!pip install -q timm lmdb safetensors pyarrow\n",
            "import base64, json, os\n",
            "PAYLOAD = '''%s'''\n" % payload(),
            "os.makedirs('/kaggle/working/src', exist_ok=True)\n",
            "for name, b64 in json.loads(PAYLOAD).items():\n",
            "    with open('/kaggle/working/src/' + name, 'wb') as fh:\n",
            "        fh.write(base64.b64decode(b64))\n",
            "    print('wrote', name)\n",
            "import timm; print('timm', timm.__version__)\n",
        ),
        code(
            "# ---- 3. data: the LMDB from HF, the labels from Zenodo (size-checked) ----\n",
            "from huggingface_hub import snapshot_download\n",
            "LMDB_DIR = snapshot_download('hackelle/BigEarthNetV2-Lithuania-Summer-LMDB',\n",
            "                             repo_type='dataset', local_dir='/kaggle/working/data/ben')\n",
            "print('lmdb at', LMDB_DIR)\n",
            "import urllib.request\n",
            "PARQ = '/kaggle/working/data/metadata.parquet'\n",
            "for attempt in range(6):\n",
            "    try:\n",
            "        urllib.request.urlretrieve('https://zenodo.org/records/10891137/files/metadata.parquet?download=1', PARQ)\n",
            "    except Exception as e:\n",
            "        print('zenodo attempt', attempt, e)\n",
            "    if os.path.exists(PARQ) and os.path.getsize(PARQ) > 3_000_000:\n",
            "        break\n",
            "    time.sleep(20)\n",
            "sz = os.path.getsize(PARQ)\n",
            "assert sz > 3_000_000, 'metadata.parquet is %d bytes - a Zenodo error page, not the file' % sz\n",
            "print('metadata.parquet', sz, 'bytes (expect 3,616,349)')\n",
        ),
        code(
            "# ---- 4. smoke: 128 patches, 1 epoch, every row - proves the path in ~3 min ----\n",
            "!cd /kaggle/working/src && python dofa_reben.py --lmdb /kaggle/working/data/ben \\\n",
            "    --parquet /kaggle/working/data/metadata.parquet --out /kaggle/working/dofa_smoke --smoke\n",
            "assert os.path.exists('/kaggle/working/dofa_smoke.json'), 'smoke run wrote nothing'\n",
            "print('smoke OK  %.1f min in' % ((time.time() - T_START) / 60))\n",
        ),
        code(
            "# ---- 5. the run: all 8,775 patches, %d epochs ----\n" % a.epochs,
            "!cd /kaggle/working/src && python dofa_reben.py --lmdb /kaggle/working/data/ben \\\n",
            "    --parquet /kaggle/working/data/metadata.parquet --out /kaggle/working/dofa_reben --epochs %d\n" % a.epochs,
            "r = json.load(open('/kaggle/working/dofa_reben.json'))\n",
            "print('\\n'.join(r['log'][-12:]))\n",
            "print('total %.1f min' % ((time.time() - T_START) / 60))\n",
        ),
    ]
    nb = {"cells": cells, "nbformat": 4, "nbformat_minor": 5,
          "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
                       "language_info": {"name": "python", "version": "3.10"},
                       "kaggle": {"accelerator": "nvidiaTeslaT4", "isInternetEnabled": True, "language": "python",
                                  "sourceType": "notebook", "isGpuEnabled": True}}}
    out = os.path.join(ROOT, "train", "dofa")
    os.makedirs(out, exist_ok=True)
    with open(os.path.join(out, "dofa-kaggle.ipynb"), "w", encoding="utf-8") as fh:
        json.dump(nb, fh, indent=1)
    meta = {"id": "%s/%s" % (a.user, a.slug), "title": a.slug, "code_file": "dofa-kaggle.ipynb",
            "language": "python", "kernel_type": "notebook", "is_private": True, "enable_gpu": True,
            "enable_internet": True, "dataset_sources": [], "kernel_sources": [], "competition_sources": []}
    with open(os.path.join(out, "kernel-metadata.json"), "w", encoding="utf-8") as fh:
        json.dump(meta, fh, indent=2)
    print("wrote", out, "->", meta["id"], "| epochs", a.epochs, "| embedded", EMBED)


if __name__ == "__main__":
    main()
